# Generated by Django 5.0.2 on 2024-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_program_id_searchresults_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
